---
  title: "R Notebook"
output: html_document
---
  
```{r}
results_path = Sys.getenv("FREEZR_DESTINATION")
dge = freezr::inventory_get(tag = "DE_TERA_reclustered_no_dub") %>% readRDS
TidynessChecklist( dge ) 
gu = dge@data %>% 
  rownames %>%
  setdiff(GUIDE_NAMES) %>% 
  setdiff("dCas9_KRAB")
```

#### Find, save, and plot markers (cluster-specific)

```{r}
markers = lapply( 0:3, FindMarkers, 
                  object = dge, 
                  logfc.threshold = 0.25,  
                  test.use = "MAST", 
                  genes.use = gu  ) 
names(markers) = paste0("cluster", 0:3)
for(ii in seq_along(markers)){ 
  markers[[ii]]$gene = rownames( markers[[ii]] )
  markers[[ii]]$q_val = p.adjust(markers[[ii]]$p_val, method = "fdr", n = dge@data %>% nrow)
  markers[[ii]]$p_val_adj = NULL
}
for(ii in seq_along(markers)){ 
  markers[[ii]]$cluster = ii-1
}
SaveMarkerTables(markers, save_dir = "cluster_de_versus_all")
inventory_add(tag      = "DE_TERA_cluster_markers_versus_all", 
              extra    = "Markers for each DE TERA cluster",
              force    = T, 
              filename = file.path(results_path, "cluster_de_versus_all"))

```

Make heatmap 

```{r}
# Retrieve markers, merge, and deduplicate
fix_old_filename = function(x) gsub("cluster_de_specific", "cluster_de_versus_all", x)
markers = inventory_get("DE_TERA_cluster_markers_versus_all") %>% fix_old_filename %>% LoadMarkerTables
for(ii in seq_along(markers)){ 
  markers[[ii]]$cluster = ii-1
}
all_markers = Reduce(markers, f=rbind)
all_markers %<>% (dplyr::arrange)(-avg_logFC)
all_markers = all_markers[!duplicated(all_markers$gene),]
all_markers %<>% (dplyr::arrange)(cluster, -avg_logFC)

og = subset(all_markers, 
            ( q_val < 0.05 & abs(avg_logFC) > log2(1.5) & pct.1 > 0.1),
            select = "gene", drop = T )
DoHeatmapFast( dge ,#%>% SubsetData(cells.use = sample(dge@cell.names, 1000)),
               results_path, 
               width = 15, height = 15,
               genes.use = og, 
               genes.label = og,  
               col = colorRampPalette(c("blue", "white", "red")),
               norm_fun = function(x) standardize(x) %>% pmin(3) %>% pmax(-3),
               cluster_colors = DE_IDENT_COLORS,
               genes.preview = sample(og, 20) )
```


```{r}
markers_ps = c("NODAL", "WNT3A", "OTX2", "GSC", "FOXA2", "LIM1", "T", "EOMES", "MIXL1", "HHEX")
markers_troph = c( "CDX2", "EOMES", "HCG", "EPCAM", "FGF4", "ERR2", "TROP2" )
# save_feature_plots( dge, results_path,
#                     gene_list = markers_ps,
#                     gene_list_name = "markers_ps" )
# save_feature_plots( dge, results_path,
#                     gene_list = markers_troph,
#                     gene_list_name = "markers_troph" )
# save_feature_plots( dge, results_path,
#                     gene_list = c("POU5F1", "SOX17", "MIXL1"),
#                     gene_list_name = "markers_figure" )
# 
# save_feature_plots( dge, results_path,
#                     gene_list = c("orig.ident"),
#                     cols.use = REPLICATE_COLORS,
#                     gene_list_name = "markers_figure" )
# save_feature_plots( dge, results_path,
#                     gene_list = paste0("PC", 1:10),
#                     gene_list_name = "pca" )

```