---
title: "R Notebook"
output: html_document
---
  
  
#### Set up workspace / data
  
```{r}

library(Seurat)
library(dplyr)
library(Matrix)
library(thymusatlastools2)
results_path = Sys.getenv("FREEZR_DESTINATION")

dge_DE_TERA = freezr::inventory_get(tag = "DE_TERA_processed_plus_guide_nodub") %>% readRDS
TidynessChecklist( dge_DE_TERA ) 
```

#### ML pipeline

```{r}
#### Find variable genes, excluding guides 
dge_DE_TERA <- FindVariableGenes(object = dge_DE_TERA,
                                 mean.function = ExpMean,
                                 dispersion.function = LogVMR,
                                 x.low.cutoff = 0.0125,
                                 x.high.cutoff = 3,
                                 y.cutoff = 0.5)
dge_DE_TERA@var.genes=dge_DE_TERA@var.genes %<>% setdiff(GUIDE_NAMES)
dge_DE_TERA@var.genes=dge_DE_TERA@var.genes %<>% setdiff("dCas9_KRAB")

### regress out nUMI
dge_DE_TERA <- ScaleData(object = dge_DE_TERA, vars.to.regress = "nUMI")
dge_DE_TERA <- RunPCA(object = dge_DE_TERA,
                      pc.genes = dge_DE_TERA@var.genes,
                      do.print = TRUE,
                      pcs.print = 1:5,
                      genes.print = 5)

# visualise top genes associated with principal components
{
  pdf(file.path(results_path, "PCA_info.pdf"))
  VizPCA(object = dge_DE_TERA, pcs.use = 1:2)
  PCAPlot(object = dge_DE_TERA, dim.1 = 1, dim.2 = 2)
  PCElbowPlot(object = dge_DE_TERA)
  dev.off()
}


dge_DE_TERA <- RunTSNE(object = dge_DE_TERA,
                       dims.use = 1:15,
                       do.fast = TRUE)

{
  dir.create.nice(file.path(results_path, "featureplots"))
  pdf(file.path(results_path, "featureplots", "PCA_info.pdf"))
  TSNEPlot(object = dge_DE_TERA, do.label = F)
  dev.off()
}

SaveFeaturePlot(dge_DE_TERA, results_path, colour = "orig.ident", cols.use = REPLICATE_COLORS)
p = custom_feature_plot(dge_DE_TERA, colour = "orig.ident", cols.use = REPLICATE_COLORS)
p = p + facet_wrap(~orig.ident, ncol = 1)
ggsave(file.path(results_path, "tSNE_reps.pdf"), p, width = 7, height = 16)
SaveFeaturePlot(dge_DE_TERA, results_path, fig_name = "blank", types = c("PDF", "PDF_PNG_split"))
SaveFeaturePlot(dge_DE_TERA, results_path, colour = "ident", cols.use = DE_IDENT_COLORS, 
             types = c("pdf", "pdf_no_leg", "pdf_png_split"))
save_feature_plots(dge_DE_TERA, results_path, c("SOX17", "POU5F1", "MIXL1", paste0("ID", 1:3)), 
                   types = c("pdf", "pdf_no_leg", "pdf_png_split"))

# Compute replicate correlations
X = make_heatmap_for_table( dge_DE_TERA, 
                            genes_in_order = rownames(dge_DE_TERA@data), 
                            ident.use = "orig.ident",
                            aggregator = mean,
                            normalize = "none", 
                            norm_fun = function(x) x, 
                            return_type = "table" )
{
  pdf(file.path(results_path, "replicate_consistency.pdf"))
  r = cor(X)[1, 2]
  plot(X, main = paste0("Replicate consistency (r=", format(r, digits = 2, nsmall = 2), ")"), 
       xlab = "Rep 1\n(average log normalized expression)", 
       ylab = "Rep 2")
  dev.off()
}

dge_DE_TERA <- FindClusters(object = dge_DE_TERA,
                            reduction.type = "pca",
                            dims.use = 1:15,
                            resolution = 0.075,
                            print.output = 0,
                            save.SNN = TRUE)
dge_DE_TERA %<>% BuildClusterTree()

{
  pdf(file.path(results_path, "tSNE_Perturbcluster.pdf"), width=10, height=10)
  TSNEPlot(object = dge_DE_TERA, do.label = TRUE)
  PlotClusterTree(dge_DE_TERA)
  dev.off()
}
```

#### save seurat object

```{r}

fp = file.path( results_path, "DE_TERA_reclustered_no_dub.Robj" )
saveRDS( dge_DE_TERA, fp )
freezr::inventory_add(tag = "DE_TERA_reclustered_no_dub", force = T,
                      filename = fp,
                      extra = "Another clustering. Prior to this clustering, doublets were depleted by looking at guide amplification.")

#dge_DE_TERA = freezr::inventory_get(tag = "DE_TERA_reclustered_no_dub") %>% readRDS
```

