---
  title: "R Notebook"
output: html_document
---
  
  
  
```{r}
results_path = Sys.getenv("FREEZR_DESTINATION")
dge = freezr::inventory_get(tag = "DE_c0") %>% readRDS
TidynessChecklist( dge ) 
```

Plot guide distribution across clusters

```{r}
save_feature_plots(dge, results_path, c("res.0.1", "Phase"), axes = UMAP_AXES)
guide_freqs_by_target = get_guides_by_cluster( dge, aggregate_by_target = T, 
                                               skip = GUIDES_BLACKLIST, 
                                               ident.use = "res.0.1" )
guide_freqs_scramble  = get_guides_by_cluster( dge, aggregate_by_target = F,
                                               skip = c(GUIDES_TRT, GUIDES_BLACKLIST), 
                                               ident.use = "res.0.1" ) 
guides_by_cluster_aggr = rbind( guide_freqs_by_target, guide_freqs_scramble )
# Wipe out duplicate row from rbind operation
guides_by_cluster_aggr = guides_by_cluster_aggr[setdiff(rownames(guides_by_cluster_aggr), "Scramble1"), ]
guides_by_cluster_aggr %>% heatmap_guides_by_cluster("guides_by_cluster_aggr.pdf")
guides_by_cluster_aggr %>% calc_save_pvals("guide_vs_cluster_aggr") -> x

guides_by_cluster = get_guides_by_cluster( dge, aggregate_by_target = F, 
                                               ident.use = "res.0.1" ) 
guides_by_cluster %>% heatmap_guides_by_cluster("guides_by_cluster.pdf") 
guides_by_cluster %>% calc_save_pvals("guide_vs_cluster")
```
